config/routes.rb
Rails.application.routes.draw do
  resources :action_items
  resources :wastes do
    collection do
      get ':waste_type/reflect', to: 'wastes#reflect', as: 'reflect'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action_item.rb
class ActionItem < ApplicationRecord
  after_initialize :init

  def init
    self.state ||= 0
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/waste.rb
class Waste < ApplicationRecord
  def issues
    record = JSON.parse(content)
    record['items'].select.with_index { |_, i| record['checked'][i] }
  end

end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  before_action :set_action_item, only: [:show, :edit, :update, :destroy]

  # GET /action_items
  # GET /action_items.json
  def index
    @action_items = ActionItem.all
  end

  # GET /action_items/1
  # GET /action_items/1.json
  def show
  end

  # GET /action_items/new
  def new
    @action_item = ActionItem.new
  end

  # GET /action_items/1/edit
  def edit
  end

  # POST /action_items
  # POST /action_items.json
  def create
    @action_item = ActionItem.new(action_item_params)

    respond_to do |format|
      if @action_item.save
        format.html { redirect_to @action_item, notice: 'Action item was successfully created.' }
        format.json { render :show, status: :created, location: @action_item }
      else
        format.html { render :new }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_items/1
  # PATCH/PUT /action_items/1.json
  def update
    respond_to do |format|
      if @action_item.update(action_item_params)
        format.html { redirect_to @action_item, notice: 'Action item was successfully updated.' }
        format.json { render :show, status: :ok, location: @action_item }
      else
        format.html { render :edit }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.json
  def destroy
    @action_item.destroy
    respond_to do |format|
      format.html { redirect_to action_items_url, notice: 'Action item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_item
      @action_item = ActionItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_item_params
      params.require(:action_item).permit(:name, :content, :state, :comment)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wastes_controller.rb
class WastesController < ApplicationController
  before_action :set_waste, only: [:show, :edit, :update, :destroy]

  # GET /wastes
  # GET /wastes.json
  def index
    @wastes = Waste.all.group_by(&:waste_type)
  end

  # GET /wastes/1
  # GET /wastes/1.json
  def show
  end

  # GET /wastes/new
  def new
    @waste = Waste.new
  end

  # GET /wastes/1/edit
  def edit
  end

  # GET /wastes/:waste_type/reflect
  def reflect
    @waste_type = params[:waste_type]
    @wastes = Waste.where(waste_type: @waste_type)
  end

  # POST /wastes
  # POST /wastes.json
  def create
    @waste = Waste.new(waste_params)

    respond_to do |format|
      if @waste.save
        format.html { redirect_to @waste, notice: 'Waste was successfully created.' }
        format.json { render :show, status: :created, location: @waste }
      else
        format.html { render :new }
        format.json { render json: @waste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wastes/1
  # PATCH/PUT /wastes/1.json
  def update
    respond_to do |format|
      if @waste.update(waste_params)
        format.html { redirect_to @waste, notice: 'Waste was successfully updated.' }
        format.json { render :show, status: :ok, location: @waste }
      else
        format.html { render :edit }
        format.json { render json: @waste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wastes/1
  # DELETE /wastes/1.json
  def destroy
    @waste.destroy
    respond_to do |format|
      format.html { redirect_to wastes_url, notice: 'Waste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_waste
    @waste = Waste.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def waste_params
    params.require(:waste).permit(:waste_type, :content, :rating)
  end

end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wastes_helper.rb
module WastesHelper
  # summarize a list of wastes into a seriousness number
  def seriousness(wastes)
    wastes.inject(0) { |sum, waste| sum + waste.rating }
  end

  # collect the list of issues
  def issues(wastes)
    wastes.flat_map(&:issues).inject(Hash.new(0)) { |h, issue| h[issue] += 1; h }
  end

  # get the sum of ratings
  def rating_sum(wastes)
    wastes.inject(0) { |sum, v| sum + v.rating }
  end
end

app/views/action_items/_form.html.erb
<%= form_with(model: action_item, local: true) do |form| %>
  <% if action_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(action_item.errors.count, "error") %> prohibited this action_item from being saved:</h2>

      <ul>
      <% action_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/action_items/edit.html.erb
<h1>Editing Action Item</h1>

<%= render 'form', action_item: @action_item %>

<%= link_to 'Show', @action_item %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Action Items</h1>

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Name</th>-->
<!--      <th>Acceptance Criteria</th>-->
<!--      <th>State</th>-->
<!--      <th colspan="1"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @action_items.each do |action_item| %>
<!--      <tr>-->
<!--        <td><%#= action_item.name %></td>-->
<!--        <td><%#= action_item.content %></td>-->
<!--        <td><%#= action_item.state %></td>-->
<!--        <td><%#= link_to 'Destroy', action_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<%- @action_items.each do |action_item| %>
  <%= content_tag :action_item, '', action_item: action_item.to_json %>
<% end %>

<br>

<%= link_to 'New Action Item', new_action_item_path %>

app/views/action_items/new.html.erb
<h1>New Action Item</h1>

<%= render 'form', action_item: @action_item %>

<%= link_to 'Back', action_items_path %>

app/views/action_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @action_item.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @action_item.content %>
</p>

<p>
  <strong>State:</strong>
  <%= @action_item.state %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @action_item.comment %>
</p>

<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Retrospective</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div data-behavior="vue">
      <%= yield %>
    </div>
  </body>
</html>

app/views/wastes/_form.html.erb
<%= form_with(model: waste, local: true) do |form| %>
  <% if waste.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waste.errors.count, "error") %> prohibited this waste from being saved:</h2>

      <ul>
      <% waste.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :waste_type %>
    <%= form.text_field :waste_type %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wastes/_waste_item.html.erb
<div class="max-w-lg shadow-lg mb-10 rounded">
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2"><%= waste_type.humanize %></div>
    <p>Rating: <%= rating_sum(items) %></p>
    <%- issues(items).each do |issue, cnt| %>
      <p class="text-grey-darker text-base mb-3">
        <%= "#{issue}: #{cnt}" %>
      </p>
    <% end %>
  </div>
  <div class="px-4 pb-5">
    <%= button_to 'Review', reflect_wastes_path(waste_type), method: :get, class: 'font-bold py-2 px-4 rounded bg-blue text-white hover:bg-blue-dark' %>
  </div>
</div>

app/views/wastes/edit.html.erb
<h1>Editing Waste</h1>

<%= render 'form', waste: @waste %>

<%= link_to 'Show', @waste %> |
<%= link_to 'Back', wastes_path %>

app/views/wastes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-indigo">Wastes</h1>

<%- @wastes.sort_by { |k, v| -seriousness(v) }.each do |waste_type, items| %>
  <%= render 'waste_item', waste_type: waste_type, items: items %>
<% end %>

<br>

<%= link_to 'New Waste', new_waste_path %>

app/views/wastes/new.html.erb
<h1>Vote Waste</h1>

<div class="ml-3">
  <wrong_feature></wrong_feature>
  <mismanage_backlog></mismanage_backlog>
  <rework></rework>
  <complex_solution></complex_solution>
  <cognitive_load></cognitive_load>
  <psychological_distress></psychological_distress>
  <waiting></waiting>
  <ineffective_communication></ineffective_communication>
</div>
<%#= render 'form', waste: @waste %>


<%= link_to 'Back', wastes_path %>

app/views/wastes/reflect.html.erb
<div class="text-bold text-xl py-3 px-3"><%= @waste_type.humanize %></div>
<%- @wastes.sort_by(&:rating).reverse.each do |waste| %>
  <div class="py-5 my-2 mx-1 rounded-sm border-2 max-w-lg flex">
    <div class="w-3/4">
      <%- waste.issues.each do |issue| %>
        <p class="px-5 py-2 text-grey-darker"><%= issue %></p>
      <% end %>
    </div>
    <div class="w-1/4 text-center p-5">
      <span class="text-2xl text-blue"><%= waste.rating %></span>
    </div>
  </div>
<% end %>

<%= content_tag 'action_item_form' %>

<%= link_to 'Back', wastes_path %>

app/views/wastes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @waste.waste_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @waste.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @waste.rating %>
</p>

<%= link_to 'Edit', edit_waste_path(@waste) %> |
<%= link_to 'Back', wastes_path %>